# Load required library
library(tidyverse)

# SIMULATE DICE THROWS AND THEIR SAMPLE MEANS ---------------------------------

# Set parameters
num_sides <- 6       # Number of sides on the dice
num_simulations <- 100000  # Number of simulations

# Function to simulate dice rolls and calculate means
simulate_dice_means <- function(sample_size) {
  sample_means <- replicate(num_simulations, mean(sample(1:num_sides, sample_size, replace = TRUE)))
  return(sample_means)
}

# Create a sequence of sample sizes
sample_sizes <- c(10, 30, 60, 120, 1000, 10000)
# Simulate and collect means for each sample size
all_means <- lapply(sample_sizes, simulate_dice_means)

# Combine means and sample sizes into a data frame
data <- data.frame(
  Sample_Size = rep(sample_sizes, each = num_simulations),
  Mean = unlist(all_means)
)

# Define colors for each sample size (red to purple to blue gradient)
sample_size_colors <- colorRampPalette(c("#FF0000", "#AA00FF", "#0000FF"))(length(sample_sizes))


# Create a density plot
ggplot(data, aes(x = Mean, fill = factor(Sample_Size))) +
  geom_density(alpha = 0.2) +
  labs(title = "Densidades das Médias Amostrais de Jogadas de Dados",
       x = "Média Amostral",
       y = "Densidade") +
  scale_fill_manual(name = "Tamanho da Amostra",
                    values = sample_size_colors,
                    labels = as.character(sample_sizes)) +
  scale_x_continuous(limits = c(2.5, 4.5))

# NORMALIZE THE SAMPLE MEANS ---------------------------------------------------

# Create a dice throw
dice <- c(1,2,3,4,5,6)
m <- mean(dice) # mean
s <- sd(dice) # standard deviation

# Normalize data
normalized_values <- data %>%
  mutate(Normalized_Value = (Mean - m) / (s/sqrt(Sample_Size)))

# Create a density plot with normalized sample means 
ggplot(normalized_values, aes(x = Normalized_Value, color = factor(Sample_Size))) +
  geom_density(linewidth = 0.6, alpha = 0.4) +
  labs(title = "Densidades das Médias Amostrais Normalizadas de Jogadas de Dados",
       x = "Média Amostral",
       y = "Densidade") +
  scale_color_manual(name = "Tamanho da Amostra",
                      values = sample_size_colors,
                      labels = as.character(sample_sizes)) +
  facet_wrap(~ Sample_Size, ncol = 2)  # Create a grid with 2 columns

# Create a grid of histograms
ggplot(normalized_values, aes(x = Normalized_Value, fill = factor(Sample_Size))) +
  geom_histogram(alpha = 0.3, color = "black") +
  labs(title = "Histogramas das Médias Amostrais Normalizadas de Jogadas de Dados",
       x = "Média Amostral",
       y = "Frequência") +
  scale_fill_manual(name = "Tamanho da Amostra",
                    values = sample_size_colors,
                    labels = as.character(sample_sizes)) +
  facet_wrap(~ Sample_Size, ncol = 2)  # Create a grid with 2 columns

# COMPARING WITH STD NORMAL GENERATED BY R -------------------------------------

# Filter the data for the specified sample size
filtered_data <- normalized_values %>% filter(Sample_Size == 10000)

# Add a column of standard normal variables to filtered_data
filtered_data$Standard_Normal <- rnorm(nrow(filtered_data))

# Calculate the maximum density value of the sample data density plot
max_density_sample_data <- round(max(density(filtered_data$Normalized_Value)$y), 3)

# Create a density plot for both the standard normal and the selected sample data
ggplot(filtered_data, aes(x = Normalized_Value)) +
  geom_density(aes(color = "Sample Data"), linewidth = 1) +
  geom_density(aes(x = Standard_Normal, color = "Standard Normal"), linewidth = 1, bw = 'nrd') +
  labs(title = "Densidade das Médias Amostrais Normalizadas",
       x = "Média Amostral Normalizada",
       y = "Densidade") +
  geom_hline(yintercept = c(0.054, 0.4, max_density_sample_data), linetype = 'dashed') + # std normal intersects (0, 0.4), (-2, 0.054) and (2, 0.054)
  geom_vline(xintercept = c(2, -2), linetype = 'dashed') +
  scale_y_continuous(breaks = c(0.054, 0.4, max_density_sample_data)) +
  scale_color_manual(values = c("Sample Data" = "red", "Standard Normal" = "blue"),
                     labels = c("Sample Data (n = 10000)", "Standard Normal")) +
  theme(legend.title=element_blank())



